apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dataexplorer.fullname" . }}
data:
  minio.yaml: |
    # Visit https://docs.rilldata.com/reference/project-files/sources to learn more about Rill source files.
    
    # WARNING: You cannot change in this file currently, better to get a new one
    type: "duckdb"
    endpoint: "{{ .Values.s3.endpoint }}"
    sql: "select * from read_parquet('s3://user-{{ .Values.user.name }}/{{ .Values.s3.file}}')"
  rill.yaml: |
    compiler: rillv1
    title: "Data Explorer"
    mock_users:
    - email: {{ .Values.user.email}}
